version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hangman
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    ports:
      - "6379:6379"

