apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  PGUSER: YWRtaW4=  # Base64 encoded 'admin'
  PGPASSWORD: cGFzc3dvcmQ=  # Base64 encoded 'password'
  PGDATABASE: aGFuZ21hbg==  # Base64 encoded 'hangman'
  REDIS_PASSWORD: ZGVmYXVsdAo= #Base64 encoded 'default'
