apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
data:
  PGUSER: YWRtaW4=  # Base64 encoded 'admin'
  PGPASSWORD: cGFzc3dvcmQ=  # Base64 encoded 'password'
  PGDATABASE: aGFuZ21hbg==  # Base64 encoded 'hangman'

